### PR TITLE
[FEATURE] Migration to the changed 3d viewer implementation of Kitodo.Presentation

### PR DESCRIPTION
**Pull request by markusweigelt**
Adjustment of the 3D viewer implementation based on the changes that have already been transferred to the master branch of Kitodo.Presentation.

- https://github.com/kitodo/kitodo-presentation/pull/1259
- https://github.com/kitodo/kitodo-presentation/pull/1283
- https://github.com/kitodo/kitodo-presentation/pull/1287

### CODE REVIEW

**Comment by markusweigelt** [comment]
@beatrycze-volk For what reason is this Grunt test being conducted, and how should I fix the failing test? The changes in the global stylesheet are necessary.

**Comment by beatrycze-volk** [comment]
> @beatrycze-volk For what reason is this Grunt test being conducted, and how should I fix the failing test? The changes in the global stylesheet are necessary.

I would suspect that your version of node and the version of node used here are differing. Not log time ago @sebastian-meyer has updated it (https://github.com/slub/dfg-viewer/pull/291). Maybe take a look into it and check if you are running the same version for the build.

**Comment by markusweigelt** [comment]
I provided the file compile with node `20.16.0` but nothing changed. What I see here is just a change detection and if there are changes test fails.

**Comment by markusweigelt** [comment]
I managed to get it working now, cause I reverted the changes in `allScripts.js` to the master version. It's likely that some formatting issues were introduced when opening the file unintentionally in the IDE. Since no modifications were made to the JavaScript, the change was not necessary.

**Comment by beatrycze-volk** [comment]
@markusweigelt Please resolve merge conflicts :)

**Comment by beatrycze-volk** [comment]
Your last commit contains changes in CSS file, it needs also be rebuilt.

**Comment by markusweigelt** [comment]
Thx. Currently, there are still more errors on my end. Once I have fixed them, I will force push.

**Comment by markusweigelt** [comment]
@beatrycze-volk with the changes provided yesterday, the merge should work.

**Comment by beatrycze-volk** [comment]
> @beatrycze-volk with the changes provided yesterday, the merge should work.

Then I will test it today.

**Comment by beatrycze-volk** [comment]
Your changes look ok, but I have problem with testing. I suspect it is problem with my configuration. Could you tell me where should I insert this config and with which value?
dfg-viewer

Stack Trace:
`Tue, 13 Aug 2024 15:26:47 +0000 [CRITICAL] request="81d044a960148" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB: FE): TYPO3\CMS\Core\Configuration\Exception\ExtensionConfigurationPathDoesNotExistException, code #1509977699, file /var/www/html/public/typo3/sysext/core/Classes/Configuration/ExtensionConfiguration.php, line 109: Path 3dviewer does not exist in extension configuration- ExtensionConfigurationPathDoesNotExistException: Path 3dviewer does not exist in extension configuration, in file /var/www/html/public/typo3/sysext/core/Classes/Configuration/ExtensionConfiguration.php:109 - {"mode":"WEB","application_mode":"FE","exception_class":"TYPO3\\CMS\\Core\\Configuration\\Exception\\ExtensionConfigurationPathDoesNotExistException","exception_code":1509977699,"file":"/var/www/html/public/typo3/sysext/core/Classes/Configuration/ExtensionConfiguration.php","line":109,"message":"Path 3dviewer does not exist in extension configuration","request_url":"https://dfgviewer-dist.ddev.site/?middleware=dlf/embedded3dviewer&model=https://3d-repository.hs-mainz.de/sites/default/files/2022-07/MZ_1250_Dom_200507_ZIP/gltf/MZ_1250_Dom_200507.glb","exception":"TYPO3\\CMS\\Core\\Configuration\\Exception\\ExtensionConfigurationPathDoesNotExistException: Path 3dviewer does not exist in extension configuration in /var/www/html/public/typo3/sysext/core/Classes/Configuration/ExtensionConfiguration.php:109\nStack trace:\n#0 /var/www/extensions/kitodo-presentation/Classes/Middleware/Embedded3dViewer.php(165): TYPO3\\CMS\\Core\\Configuration\\ExtensionConfiguration->get('dlf', '3dviewer')\n#1 /var/www/extensions/kitodo-presentation/Classes/Middleware/Embedded3dViewer.php(77): Kitodo\\Dlf\\Middleware\\Embedded3dViewer->getViewerByExtensionConfiguration('glb')\n#2 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): Kitodo\\Dlf\\Middleware\\Embedded3dViewer->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#3 /var/www/extensions/dfg-viewer/Classes/Middleware/SruMiddleware.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#4 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): `

**Comment by markusweigelt** [comment]
For testing, it is sufficient to simply save the dlf extension configuration. Otherwise, I have provided a bugfix PR for Kitodo-Presentation https://github.com/kitodo/kitodo-presentation/pull/1297. If you switch the Kitodo.Presentation extension to this branch of the PR, it should work for you.

**Comment by markusweigelt** [comment]
Do you have the ‘tx_dlf_modeldownloadtool’ plugin in your kitodo.typoscript, i.e. are you using the one from the PR? If you run Kitodo.Presentation with the state of master or the missing-extension-config branch it should work. Maybe you can flush all caches.

It tested the implementation on my local environment with your mets and it seams to work `https://ddev-dfgviewer.ddev.site/viewer?tx_dlf[id]=https://3d-repository.hs-mainz.de/sites/default/files/xml_structure/59.xml`.

**Comment by markusweigelt** [comment]
The browser does not download the model in repository of `3d-repository.hs-mainz.de` but instead redirects to the modell in the Mainz repository. 
This is due to the issue I just reported. https://github.com/slub/dlf-3d-viewers/issues/76

**Review by beatrycze-volk — APPROVED** [review]

**Pull request merged**
