### PR TITLE
Revert "Update GitHub actions which still used deprecated Node.js"

### PR DESCRIPTION
**Pull request by beatrycze-volk**
Reverts slub/dfg-viewer#292

### CODE REVIEW

**Comment by stweil** [comment]
Why did you revert my commit, just to apply the same changes again in commit 9a5adb50f4467de428b1ddf5169db7c224deb0ba?

**Comment by beatrycze-volk** [comment]
I needed to revert all changes introduced after https://github.com/slub/dfg-viewer/pull/230 in order to revert it, After reverting it I wanted to avoid loss of the changes introduced. So I have created the PR containing all changes related to Node JS https://github.com/slub/dfg-viewer/pull/304.

**Comment by stweil** [comment]
It would have been sufficient and much easier to revert only the changes from PR #230, perhaps with manual fixes for a small number of conflicts.

**Comment by beatrycze-volk** [comment]
It was not possible. I tried to do it that way. I got error message that because of the changes made after the https://github.com/slub/dfg-viewer/pull/230, the revert PR can not be created. So I have decided to revert changes one by one.

**Pull request merged**
