### PR TITLE
Update generated CSS and JS files

### PR DESCRIPTION
**Pull request by sebastian-meyer**
* Add dependency `grunt-cli` to `Build/package.json`
* Update dependencies in `Build/package-lock.json`
* Use node.js 20.x for grunt workflow
* Update generated CSS and JS files (running `grunt less` & `grunt terser`)

This completes PR #230.

### CODE REVIEW

**Comment by stweil** [comment]
Grunt 1.6.1 (in your package-lock.json) requires Node.js 14 or later.

**Comment by stweil** [comment]
It seems to work with Node.js 18, but then creates a different Resources/Public/Css/allStyles.css.map.

**Comment by sebastian-meyer** [comment]
Finally! Thank you for your assistance, @stweil!

**Comment by sebastian-meyer** [comment]
GitHub doesn't allow reviewing my own PRs and also doesn't allow me to merge this without a review. Could you please have a look at this when you are back in office, @beatrycze-volk?

**Review by stweil — APPROVED** [review]

**Comment by gnuj** [comment]
Good work! 👍  I also dug a little deeper yesterday and found one or two other NPM issues, which also would be solved by raising the node.js version. So no additions from my side.

**Comment by beatrycze-volk** [comment]
@stweil and @sebastian-meyer thank you for solving this problem :)

**Review by beatrycze-volk — APPROVED** [review]

**Pull request merged**
