### PR TITLE
Rename cofiguration for tools to match changes in Kitodo Presentation

### PR DESCRIPTION
**Pull request by beatrycze-volk**
This PR is a fix for problem reported here: https://github.com/kitodo/kitodo-presentation/issues/994

### CODE REVIEW

**Comment by stweil** [comment]
@csidirop, please test this fix.
@beatrycze-volk, maybe you want to fix the typo in the commit message.

**Comment by csidirop** [comment]
I must be doing something wrong because I don't see any change. I merged #235 and #234 into [master](https://github.com/slub/dfg-viewer), flushed caches and did a full site reload. 

Did I missed something?

Sitenote: I tried this in our Docker environment, so that I have a clean state for my tests.

**Comment by csidirop** [comment]
Okay thanks! I'll test it tomorrow.

**Comment by csidirop** [comment]
Works fine again! Thanks :)

**Review by stweil — APPROVED** [review]
Thanks. Test at UB Mannheim was successful.

**Pull request merged**
